# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backrest < Formula
  desc "Backrest is a web UI and orchestrator for restic backup."
  homepage "https://github.com/garethgeorge/backrest"
  version "1.6.1"

  on_macos do
    on_intel do
      url "https://github.com/garethgeorge/backrest/releases/download/v1.6.1/backrest_Darwin_x86_64.tar.gz"
      sha256 "f680f3a46cbbf6087d09cfa387d71ac9268d53f94da058717f2810bf57092ee1"

      def install
        bin.install "backrest"
      end
    end
    on_arm do
      url "https://github.com/garethgeorge/backrest/releases/download/v1.6.1/backrest_Darwin_arm64.tar.gz"
      sha256 "651f154bb97fe92a5984b6a4824dd9f74676e609ac7a825ec082da29f621d5fe"

      def install
        bin.install "backrest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garethgeorge/backrest/releases/download/v1.6.1/backrest_Linux_x86_64.tar.gz"
        sha256 "721856c8a5a59903ab22acc8cc57b042567bebe120b03576447b4b84f4861ad5"

        def install
          bin.install "backrest"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/garethgeorge/backrest/releases/download/v1.6.1/backrest_Linux_armv6.tar.gz"
        sha256 "a81014463b0a297788b298fb116bafebf6168bb90eb7f0ef62a4feccb4402bb9"

        def install
          bin.install "backrest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garethgeorge/backrest/releases/download/v1.6.1/backrest_Linux_arm64.tar.gz"
        sha256 "01f536fee912cc98adb4f5b552606cce620e30445f5548b32a9f980a9fe2d020"

        def install
          bin.install "backrest"
        end
      end
    end
  end

  service do
    run opt_bin/"backrest"
    error_log_path var/"log/backrest.log"
    log_path var/"log/backrest.log"
  end
end
