# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backrest < Formula
  desc "Backrest is a web UI and orchestrator for restic backup."
  homepage "https://github.com/garethgeorge/backrest"
  version "1.11.1"

  on_macos do
    on_intel do
      url "https://github.com/garethgeorge/backrest/releases/download/v1.11.1/backrest_Darwin_x86_64.tar.gz"
      sha256 "1c872c79d50de6257907df7069dad4be2aa40c51b6708b9ae5c1f6037f33550a"

      def install
        bin.install "backrest"
      end
    end
    on_arm do
      url "https://github.com/garethgeorge/backrest/releases/download/v1.11.1/backrest_Darwin_arm64.tar.gz"
      sha256 "3f60163830c1edce302720517b1ac20ce33fd237c7882429fd116e01316897c8"

      def install
        bin.install "backrest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garethgeorge/backrest/releases/download/v1.11.1/backrest_Linux_x86_64.tar.gz"
        sha256 "d5de2cf4d505af807b5661063ca2016d2ea42af2ffe17405ca1668626ea3971d"

        def install
          bin.install "backrest"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/garethgeorge/backrest/releases/download/v1.11.1/backrest_Linux_armv6.tar.gz"
        sha256 "4859c14302bdba2477c16371e07b787db09a20fba6f53374502fe8b70ad1787c"

        def install
          bin.install "backrest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/garethgeorge/backrest/releases/download/v1.11.1/backrest_Linux_arm64.tar.gz"
        sha256 "c93f49423a06a80ef2f022f630c628293e6d1be8e748ebc27aa30f0ccf30cf04"

        def install
          bin.install "backrest"
        end
      end
    end
  end

  service do
    run opt_bin/"backrest"
    error_log_path var/"log/backrest.log"
    log_path var/"log/backrest.log"
  end
end
